config/routes.rb
Tea::Application.routes.draw do

  resources :step_statuses

  resources :steps

  resources :test_cases

  resources :versions

  resources :test_types

  resources :risks

  resources :priorities

  resources :statuses

  resources :test_items

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "signed_out" => "authentication#signed_out"
  get "forgot_password" => "authentication#forgot_password"
  get "password_sent" => "authentication#password_sent"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"

  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"

  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"

  get "role_settings" => "authentication#role_settings"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"

  get "new_role" => "authentication#new_role"
  post "new_role" => "authentication#new_role"
  put "new_role" => "authentication#create_role"

  get "admin_roles" => "admin#roles"
  delete "role/:id" => "admin#delete_role", :as => "role"

end

app/controllers/step_statuses_controller.rb
class StepStatusesController < ApplicationController
  before_action :set_step_status, only: [:show, :edit, :update, :destroy]

  # GET /step_statuses
  # GET /step_statuses.json
  def index
    @step_statuses = StepStatus.all
  end

  # GET /step_statuses/1
  # GET /step_statuses/1.json
  def show
  end

  # GET /step_statuses/new
  def new
    @step_status = StepStatus.new
  end

  # GET /step_statuses/1/edit
  def edit
  end

  # POST /step_statuses
  # POST /step_statuses.json
  def create
    @step_status = StepStatus.new(step_status_params)

    respond_to do |format|
      if @step_status.save
        format.html { redirect_to @step_status, notice: 'Step status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @step_status }
      else
        format.html { render action: 'new' }
        format.json { render json: @step_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /step_statuses/1
  # PATCH/PUT /step_statuses/1.json
  def update
    respond_to do |format|
      if @step_status.update(step_status_params)
        format.html { redirect_to @step_status, notice: 'Step status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @step_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /step_statuses/1
  # DELETE /step_statuses/1.json
  def destroy
    @step_status.destroy
    respond_to do |format|
      format.html { redirect_to step_statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_step_status
      @step_status = StepStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def step_status_params
      params.require(:step_status).permit(:stepstatus_name)
    end
end

app/helpers/step_statuses_helper.rb
module StepStatusesHelper
end

app/views/step_statuses/_form.html.erb
<%= form_for(@step_status) do |f| %>
  <% if @step_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step_status.errors.count, "error") %> prohibited this step_status from being saved:</h2>

      <ul>
      <% @step_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="container">

          <div class="field">
            <%= f.label :stepstatus_name %><br>
            <%= f.text_field :stepstatus_name %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>

    </div>

<% end %>

app/views/step_statuses/edit.html.erb
<h1>Editing step_status</h1>

<%= render 'form' %>

<%= link_to 'Show', @step_status %> |
<%= link_to 'Back', step_statuses_path %>

app/views/step_statuses/index.html.erb
<h1>Step Statuses</h1>

<table class="table3">
  <thead>
    <tr>
      <th>Stepstatus Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @step_statuses.each do |step_status| %>
      <tr>
        <td><%= step_status.stepstatus_name %></td>
        <td><%= link_to 'Show', step_status %></td>
        <td><%= link_to 'Edit', edit_step_status_path(step_status) %></td>
        <td><%= link_to 'Destroy', step_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step status', new_step_status_path %>

app/views/step_statuses/new.html.erb
<h1>New Step Status</h1>

<%= render 'form' %>

<%= link_to 'Back', step_statuses_path %>

app/views/step_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stepstatus name:</strong>
  <%= @step_status.stepstatus_name %>
</p>

<%= link_to 'Edit', edit_step_status_path(@step_status) %> |
<%= link_to 'Back', step_statuses_path %>