config/routes.rb
Tea::Application.routes.draw do

  resources :step_statuses

  resources :steps

  resources :test_cases

  resources :versions

  resources :test_types

  resources :risks

  resources :priorities

  resources :statuses

  resources :test_items

  root  'static_pages#home'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  get "signed_out" => "authentication#signed_out"
  get "forgot_password" => "authentication#forgot_password"
  get "password_sent" => "authentication#password_sent"

  get "sign_in" => "authentication#sign_in"
  post "sign_in" => "authentication#login"

  get "new_user" => "authentication#new_user"
  post "new_user" => "authentication#register"
  put "new_user" => "authentication#register"

  get "account_settings" => "authentication#account_settings"
  put "account_settings" => "authentication#set_account_info"

  get "role_settings" => "authentication#role_settings"

  get "forgot_password" => "authentication#forgot_password"
  put "forgot_password" => "authentication#send_password_reset_instructions"
  get "password_reset" => "authentication#password_reset"
  put "password_reset" => "authentication#new_password"

  get "admin_users" => "admin#users"
  delete "user/:id" => "admin#delete_user", :as => "user"

  get "new_role" => "authentication#new_role"
  post "new_role" => "authentication#new_role"
  put "new_role" => "authentication#create_role"

  get "admin_roles" => "admin#roles"
  delete "role/:id" => "admin#delete_role", :as => "role"

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_filter :authenticate_user, :only => [:account_settings, :set_account_info, :role_settings]

  def sign_in
    @user = User.new
  end

  # ========= Signing In ==========

  def login
    username_or_email = params[:user][:username]
    user = verify_user(username_or_email)

    if user
      update_authentication_token(user, params[:user][:remember_me])
      user.last_signed_in_on=DateTime.now
      user.save
      session[:user_id] = user.id
      flash[:notice] = 'Welcome.'
      redirect_to :root
    else
      flash.now[:error] = 'Unknown user.  Please check your username and password.'
      render :action => "sign_in"
    end
  end

  # ========= Signing Out ==========

  def signed_out
    # clear the authentication toke when the user manually signs out
    user = User.find_by_id(session[:user_id])

    if user
      update_authentication_token(user, nil)
      user.save
      session[:user_id] = nil
      flash[:notice] = "You have been signed out."
    else
      redirect_to :sign_in
    end
  end

  # ========= Handles Registering a New User ==========

  def new_user
    @user = User.new
    @roles = Role.all
  end

  def register
    @user = User.new(params[:user])

    # Don't use !verify_recaptcha, as this terminates the connection with the server.
    # It almost seems as if the verify_recaptcha is being called twice with we use "not".
    if verify_recaptcha
      if @user.valid?
        update_authentication_token(@user, nil)
        @user.signed_up_on = DateTime.now
        @user.last_signed_in_on = @user.signed_up_on
        @user.save
        # UserMailer.welcome_email(@user).deliver
        session[:user_id] = @user.id
        flash[:notice] = 'Welcome.'
        redirect_to :root
      else
        render :action => "new_user"
      end
    else
      flash.delete(:recaptcha_error)  
      # get rid of the recaptcha error being flashed by the gem.
      flash.now[:error] = 'reCAPTCHA is incorrect.  Please try again.'
      render :action => "new_user"
    end
  end

  # ========= Handles Changing Account Settings ==========

  def account_settings
    @user = current_user
  end

  def set_account_info
    old_user = current_user

    # verify the current password by creating a new user record.
    @user = User.authenticate_by_username(old_user.username, params[:user][:password])

    # verify
    if @user.nil?
      @user = old_user
      @user.errors[:password] = "Password is incorrect."
      render :action => "account_settings"
    else
      # update the user with any new username and email
      @user.update(params[:user])
      # Set the old email and username, which is validated only if it has changed.
      @user.previous_email = old_user.email
      @user.previous_username = old_user.username

      if @user.valid?
        # If there is a new_password value, then we need to update the password.
        @user.password = @user.new_password unless @user.new_password.nil? || @user.new_password.empty?
        @user.save
        flash[:notice] = 'Account settings have been changed.'
        redirect_to :root
      else
        render :action => "account_settings"
      end
    end
  end

  # ========= Handles Password Reset ==========

  # HTTP get
  def forgot_password
    @user = User.new
  end

  # HTTP put
  def send_password_reset_instructions
    username_or_email = params[:user][:username]

    if username_or_email.rindex('@')
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user
      user.password_reset_token = SecureRandom.urlsafe_base64
      user.password_expires_after = 24.hours.from_now
      user.save
      UserMailer.reset_password_email(user).deliver
      flash[:notice] = 'Password instructions have been mailed to you.  Please check your inbox.'
      redirect_to :sign_in
    else
      @user = User.new
      # put the previous value back.
      @user.username = params[:user][:username]
      @user.errors[:username] = 'Is Not a Registered User.'
      render :action => "forgot_password"
    end
  end

  # The user has landed on the password reset page, they need to enter a new password.
  # HTTP get
  def password_reset
    token = params.first[0]
    @user = User.find_by_password_reset_token(token)

    if @user.nil?
      flash[:error] = 'You have not requested a password reset.'
      redirect_to :root
      return
    end

    if @user.password_expires_after < DateTime.now
      clear_password_reset(@user)
      @user.save
      flash[:error] = 'Password reset has expired.  Please request a new password reset.'
      redirect_to :forgot_password
    end
  end

  # The user has entered a new password.  Need to verify and save.
  # HTTP put
  def new_password
    username = params[:user][:username]
    @user = User.find_by_username(username)

    if verify_new_password(params[:user])
      @user.update(params[:user])
      @user.password = @user.new_password

      if @user.valid?
        clear_password_reset(@user)
        @user.save
        flash[:notice] = 'Your password has been reset.  Please sign in with your new password.'
        redirect_to :sign_in
      else
        render :action => "password_reset"
      end
    else
      @user.errors[:new_password] = 'Cannot be blank and must match the password verification.'
      render :action => "password_reset"
    end
  end

# ========== Role stuff ================
  def new_role
    @role = Role.new
  end

  def role_settings
    @role = Role.all
    render :action => "role_setting"
   # @role = Role.find(params[:id])
  end
 
 def set_role_info
    # old_role = current_role
    # update the role
    @role.update(params[:role])
    @role.save
        flash[:notice] = 'Role settings have been changed.'
        redirect_to :root
         # render :action => "role_settings"
 end
  


# POST /roles
  # POST /roles.json
  def create_role
    @role = Role.new(params[:role])

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render action: 'show', status: :created, location: @role }
      else
        format.html { render action: 'new_role' }
        format.json { render json: @new_role.errors, status: :unprocessable_entity }
      end
    end
  end



  # ========= Private Functions ==========

  private

  def clear_password_reset(user)
    user.password_expires_after = nil
    user.password_reset_token = nil
  end

  def verify_new_password(passwords)
    result = true

    if passwords[:new_password].blank? || (passwords[:new_password] != passwords[:new_password_confirmation])
      result=false
    end

    result
  end

  # Verifies the user by checking their email and password or their username and password
  def verify_user(username_or_email)
    password = params[:user][:password]
    if username_or_email.rindex('@')
      email=username_or_email
      user = User.authenticate_by_email(email, password)
    else
      username=username_or_email
      user = User.authenticate_by_username(username, password)
    end

    user
  end

  def update_authentication_token(user, remember_me)
    if remember_me == 1
      # create an authentication token if the user has clicked on remember me
      auth_token = SecureRandom.urlsafe_base64
      user.authentication_token = auth_token
      cookies.permanent[:auth_token] = auth_token
    else              # nil or 0
                      # if not, clear the token, as the user doesn't want to be remembered.
      user.authentication_token = nil
      cookies.permanent[:auth_token] = nil
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :role_mask, :password, :password_confirmation, :new_password, :new_password_confirmation, :remember_me)
  end

  def set_role
    @role = Role.find(params[:id])
  end

  def role_params
    params.require(:role).permit(:name, :description)
  end

end

app/views/authentication/account_settings.html.erb
<h1>Account Settings</h1>
<div class="container">

    <%= form_for @user, :as => :user, :url => account_settings_path, :method => :put do |f| %>
        <p>
          <%= f.label 'current password:' %><br/>
          <%= f.password_field :password %>
          <%= show_field_error(@user, :password) %>
        </p>
        <p>
          <%= f.label 'username: (leave unchanged if you are not changing your username)' %><br/>
          <%= f.text_field :username %>
          <%= show_field_error(@user, :username) %>
        </p>
        <p>
          <%= f.label 'email: (leave unchanged if you are not changing your email address)' %><br/>
          <%= f.text_field :email %>
          <%= show_field_error(@user, :email) %>
        </p>
        <p>
          <%= f.label 'Role:' %><br/>
          <%#= f.text_field :roles_mask %>
          <%= f.collection_select(:roles_mask, Role.all, :name, :name , {prompt: "Select a Role"},{:selected => "User"}) %>
          <%#= show_field_error(@role, :roles_mask) %>
        </p>
        <p>
          <%= f.label 'new password: (leave blank if you are not changing your password)' %><br/>
          <%= f.password_field :new_password %>
          <%= show_field_error(@user, :new_password) %>
        </p>
        <p>
          <%= f.label 'password confirmation:' %><br/>
          <%= f.password_field :new_password_confirmation %>
          <%= show_field_error(@user, :new_password_confirmation) %>
        </p>
        
        <p>
          <%= f.submit 'Update', class: "btn btn-medium btn-primary" %>
        </p>
    <% end %>
 </div>

app/views/authentication/change_password.html.erb
<h1>Change Password</h1>

app/views/authentication/forgot_password.html.erb
<h1>Forgot Password</h1>
<%= form_for @user, :as => :user, :url => forgot_password_path, :method => :put do |f| %>
    <p>
      <%= f.label 'username or email:' %><br/>
      <%= f.text_field :username %>
      <%= show_field_error(@user, :username) %>
    </p>
    <p>
       <%= f.submit 'Send Password Reset Instructions',class: "btn btn-medium btn-primary" %>
    </p>
<% end %>

app/views/authentication/new_role.html.erb
<h1>New Role</h1>
<div class="container">

    <%= form_for(@role, :url => new_role_path) do |f| %>
        <p>
          <%= f.label 'Name:' %><br/>
          <%= f.text_field :name %>
          <%= show_field_error(@role, :name) %>
        </p>
        <p>
          <%= f.label 'Description:' %><br/>
          <%= f.text_field :description%>
          <%= show_field_error(@role, :description) %>
        </p>
        
        <p>
          <%= f.submit %><br>
          <%= f.submit 'Clear Form', class: "btn btn-medium btn-primary", :type => 'reset' %>
        </p>
    <% end %>
  </div>

app/views/authentication/new_user.html.erb
<h1>New User</h1>
<div class="container">

    <%= form_for @user, :as => :user, :url => new_user_path, :method => :put do |f| %>
        <p>
          <%= f.label 'Username:' %><br/>
          <%= f.text_field :username %>
          <%= show_field_error(@user, :username) %>
        </p>
        <p>
          <%= f.label 'Email:' %><br/>
          <%= f.text_field :email %>
          <%= show_field_error(@user, :email) %>
        </p>
        <p>
          <%= f.label 'Password:' %><br/>
          <%= f.password_field :password %>
          <%= show_field_error(@user, :password) %>
        </p>
        <p>
          <%= f.label 'Password Confirmation:' %><br/>
          <%= f.password_field :password_confirmation %>
          <%= show_field_error(@user, :password_confirmation) %>
        </p>
        <p>
          <%= f.label 'Role:' %><br/>
          <%#= f.text_field :roles_mask %>
          <%= f.collection_select(:roles_mask, Role.all, :name, :name , {prompt: "Select a Role"},{:selected => "User"}) %>
          <%#= show_field_error(@role, :roles_mask) %>
        </p>
        <p>
          <%= f.check_box :remember_me, class: "btn btn-medium btn-primary" %>
          <%= f.label 'remember me' %>
        
        <p>
         <%= recaptcha_tags %>
        </p>
        <p>
          <%= f.submit 'Sign Up', class: "btn btn-medium btn-primary" %>&nbsp;&nbsp;&nbsp;
          <%= f.submit 'Clear Form', class: "btn btn-medium btn-primary", :type => 'reset' %>
        </p>
    <% end %>
  </div>

app/views/authentication/password_reset.html.erb
<p>Account Settings</p>
<%= form_for @user, :as => :user, :url => password_reset_path, :method => :put do |f| %>
    <p>
      <%= @user.username %> has requested a password reset. Please enter your new password:
    </p>
    <p>
      <%= f.label 'new password:' %><br/>
      <%= f.password_field :new_password %>
      <%= show_field_error(@user, :new_password) %>
    </p>
    <p>
      <%= f.hidden_field :username %>
      <%= f.label 'password confirmation:' %><br/>
      <%= f.password_field :new_password_confirmation %>
      <%= show_field_error(@user, :new_password_confirmation) %>
    </p>
    <p>
      <%= f.submit 'Update' %>
    </p>
<% end %>

app/views/authentication/password_sent.html.erb
<h1>Password Sent</h1>

app/views/authentication/reset_password_email.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
</head>
<body>
<p>
  <%= @user.username %> has requested a password reset.
</p>
<p>
  To reset your password, click the URL below.
</p>
<p>
  <%= @password_reset_url %>
</p>
<p>
  If you did not request your password to be reset, just ignore this email and your password will continue to stay the same.
</p>
</body>
</html>

app/views/authentication/show_role.html.erb
<% for column in Role.content_columns %>
<p>
  <b><%= column.human_name %>:</b> <%=h @role.send(column.name) %>
</p>
<% end %>
<p>
  <b>Role(s):</b> <%=h @user.roles.collect {|r| r.name}.join(', ') %>
</p>
<%= link_to 'Edit', :action => 'edit', :id => @role %> |
<%= link_to 'Back', :action => 'list' %>

app/views/authentication/show_user.html.erb
<% for column in User.content_columns %>
<p>
  <b><%= column.human_name %>:</b> <%=h @user.send(column.name) %>
</p>
<% end %>
<p>
  <b>Role(s):</b> <%=h @user.roles.collect {|r| r.name}.join(', ') %>
</p>
<%= link_to 'Edit', :action => 'edit', :id => @user %> |
<%= link_to 'Back', :action => 'list' %>

app/views/authentication/sign_in.html.erb
<h1>Sign In</h1>

<div class="registration-container col-md-6">


    <%= form_for User.new, :as => :user, :url => sign_in_path do |f| %>
      <div class="field">
          <%= f.label 'username or email:' %><br>
          <%= f.text_field :username %>
      </div>
      <div class="field">
          <%= f.label 'password:' %><br/>
          <%= f.password_field :password %>
      </div>
      <div class="checkbox-inline">
        <%= f.label 'remember me' %>
        <%= f.check_box :remember_me %>
      </div>
      <div> <br> </div>
      <div class="form-actions">
        <div class="col-md-5">
          <div class="field">
              <%= f.submit 'Sign In', class: "btn btn-medium btn-primary" %>&nbsp;&nbsp;&nbsp;
              <%= f.submit 'Clear Form',  class: "btn btn-medium btn-primary", :type => 'reset' %>
              <div> <br> </div>
              <%= link_to 'forgot your password?', :forgot_password %>
            </div>
         </div>
      </div>

    <% end %>
</div>

app/views/authentication/signed_out.html.erb
<h1>Signed Out</h1>
<div class="center">
<%= link_to image_tag("CBlogo.png", alt: "ClickBank"), 'http://www.clickbank.com' %>
</div>
<h3>Thanks for Visiting</h3>